### ISSUE TITLE
cannot load such file -- bundler

### ISSUE THREAD

**Issue by mightydok** [rogeriopradoj/vagrant-ip-show#6]
Cant run vagrant after plugin install, log after:
Vagrant 1.9.1

```
E:\Work\vagrant\graphite>vagrant plugin install vagrant-ip-show
Installing the 'vagrant-ip-show' plugin. This can take a few minutes...
Fetching: vagrant-ip-show-0.0.4.gem (100%)
Installed the plugin 'vagrant-ip-show (0.0.4)'!

E:\Work\vagrant\graphite>vagrant status
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- bundler
```

**Comment by mightydok** [comment]
Can i comment out this require?
```
require 'bundler'
```
in lib/vagrant-ip-show.rb file?

**Comment by briantully** [comment]
same here

**Comment by artdevjs** [comment]
the same(

**Comment by cheetooh** [comment]
i am facing the same issue...

**Comment by rogeriopradoj** [comment]
Hi, sorry for taking so long.

Please do this to fix:
- update your vagrant to latest version (today is 2.0.1) on https://www.vagrantup.com/
- run `vagrant plugin repair`
- optionally, run `vagrant plugin update` or `vagrant plugin expunge --reinstall`

Please, let me know if you are facing the same issue, ok?

@mightydok 
@briantully
@artdevjs 
@cheetooh 

Best!
